spring.datasource.url=jdbc:mysql://localhost:3306/agenda?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=automationcode
spring.datasource.password=JavaDev@2026
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
server.address=127.0.0.1


aw.storage.s3.key-id = ${OCI_S3_KEY_ID}
aw.storage.s3.key-secret = ${OCI_S3_KEY_SECRET}
aw.storage.s3.bucket = ${OCI_S3_BUCKET}
aw.storage.s3.region = ${OCI_S3_REGION}
aw.storage.s3.endpoint = ${OCI_S3_ENDPOINT}