name: Deploy Agenda Ai
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build (Maven)
        run: mvn clean package -DskipTests

      - name: Atualizar JAR e reiniciar
        run: |
          sudo cp target/*.jar /var/app/app.jar
          sudo systemctl restart agenda-ai
